import Head from "next/head";
import Image from "next/image";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub, AiFillMail } from "react-icons/ai";
import { DiHtml5, DiCss3Full, DiReact, DiJava, DiPython, DiPostgresql, DiGit } from "react-icons/di";
import { IoLogoJavascript, IoLogoFirebase } from "react-icons/io5";
import { SiSpringboot, SiPostman, SiTailwindcss } from "react-icons/si"
import face1 from "../public/face-1.jpg";
import face3 from "../public/face-4.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import { useState } from "react";
import worldpinimage from "../public/worldpin-image.png";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Faizan Khan Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-2 sm:px-10 md:px-20 lg:px-40 dark:bg-gray-900 scroll-smooth">
        <section className="">
          <nav className="pt-8 sm:py-10">
            <ul className=" space-y-8 flex-col place-items-center flex sm:space-y-0 sm:flex-row sm:justify-between  
              lg:px-4 xl:px-40">
              <li>
                <a
                  className="
                  bg-gradient-to-r  from-cyan-500 to-teal-500 font-bold text-white px-4 py-2 rounded-md 
                  hover:from-cyan-700 hover:to-teal-700
                  dark:bg-gradient-to-r dark:from-orange-400 dark:to-pink-400 
                  dark:hover:from-orange-600 dark:hover:to-pink-600
                  "
                  href= "https://drive.google.com/file/d/1HePbe5Go0os8pzI5kaoU90dwaOdp_aWT/view?usp=pdf"
                  target="_blank"
                >
                  &nbsp; CV &nbsp;
                </a>
              </li>
              <li>
                <a
                  className="
                  bg-gradient-to-r from-cyan-500 to-teal-500 font-bold text-white px-4 py-2 rounded-md 
                  hover:from-cyan-700 hover:to-teal-700
                  dark:bg-gradient-to-r dark:from-orange-400 dark:to-pink-400 
                  dark:hover:from-orange-600 dark:hover:to-pink-600"
                  href="#about-me"
                >
                  About Me
                </a>
              </li>
              <li>
                <a
                  className="
                  bg-gradient-to-r from-cyan-500 to-teal-500 font-bold text-white px-4 py-2 rounded-md 
                  hover:from-cyan-700 hover:to-teal-700
                  dark:bg-gradient-to-r dark:from-orange-400 dark:to-pink-400 
                  dark:hover:from-orange-600 dark:hover:to-pink-600"
                  href="#projects"
                >
                  Projects
                </a>
              </li>

              <div >
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=
                  "cursor-pointer text-2xl text-gray-800 hover:scale-125 dark:text-white transition-all"
                />
              </div>
            </ul>
          </nav>
        </section>

        <section>

          <div className="text-center sm:px-10 sm:my-10 my-8">
            <h2 className="text-4xl md:text-5xl py-3 text-teal-600 font-medium  dark:text-pink-400">
              Hi, I'm Faizan Ahmed Khan
            </h2>
            <h3 className="text-2xl pt-3 text-black md:text-3xl dark:text-white">
              Full-Stack Software Developer
            </h3>
            <p className="py-5 leading-8 text-gray-800 md:text-xl dark:text-gray-300">
              I love exploring and creating <br />
              I'm a lifelong learner <br />
              <span className="">
                Looking for opportunities in the industry
              </span>
            </p>
          </div>

          <div className=
          "text-4xl sm:text-5xl flex justify-center gap-16 text-gray-600 dark:text-white">
            <a
              href="https://www.linkedin.com/in/faizanahmkhan/"
              target="_blank"
            >
              <AiFillLinkedin className="hover:text-blue-500 hover:scale-110" />
            </a>
            <a href="https://github.com/faizanahmkhan" target="_blank">
              <AiFillGithub className="hover:text-gray-400 hover:scale-110" />
            </a>
            <a href="mailto:faizanahmkhan@gmail.com">
              <AiFillMail className="hover:text-yellow-400 hover:scale-110 " />
            </a>
          </div>

          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 sm:w-80 sm:h-80 mt-6 sm:mt-20 overflow-hidden md:h-96 md:w-96">
            {darkMode ? (
              <Image src={face3} layout="fill" objectFit="cover" />
            ) : (
              <Image src={face1} layout="fill" objectFit="cover" />
            )}
          </div>

        </section>

        <section className="mt-10">
          <div>
            <h3 id='about-me' className="text-center text-4xl md:text-5xl font-medium py-10 text-black dark:text-white">
              About Me
            </h3>
            <h2 className="text-center text-2xl md:text-3xl font-semibold text-teal-600 mt-6 mb-4 dark:text-pink-400">
              Background
            </h2>
            <div className="flex">
              <p className="xl:w-1/5"></p>
              <p className=" text-center sm:text-lg px-4 sm:px-0 py-2 leading-8 sm:leading-10 text-gray-800 xl:w-3/5 dark:text-gray-300">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                Eligendi cum ea temporibus,{" "}
                <span className="text-teal-400"> facilis voluptates sint</span>{" "}
                eum voluptatibus dolorum, doloremque iure maxime quia obcaecati
                dolorem eius modi. Laborum corporis molestias laboriosam
                reprehenderit? Voluptate nobis, minima inventore repellendus
                deserunt cupiditate obcaecati repellat.
              </p>
              <p className="xl:w-1/5"></p>
            </div>
          </div>

          <div>
            <h2 className="text-center text-2xl md:text-3xl font-semibold text-teal-600 m-14 dark:text-pink-400">
              Skills & Tools
            </h2>


            <div className="grid grid-cols-4 lg:max:xl:px-30 xl:px-56">
        
              <div className="text-gray-600  dark:text-white flex flex-col justify-center items-center">
                <DiCss3Full 
                className="text-gray-600 text-4xl sm:text-5xl hover:text-blue-700 hover:scale-110 dark:text-white
                dark:hover:text-blue-700 " />
                
                <span className="font-medium hover:text-blue-700">CSS</span>
              </div>

              <div className="text-gray-600 dark:text-white flex flex-col justify-center items-center">
              <DiHtml5 
              className="text-gray-600 text-4xl sm:text-5xl hover:text-orange-400 hover:scale-110 dark:text-white
                 dark:hover:text-orange-400" 
                />
              <span className="font-medium hover:text-orange-400">HTML</span>  
              </div>

              <div className="text-gray-600 dark:text-white flex flex-col justify-center items-center">
              <IoLogoJavascript 
              className="text-gray-600 text-4xl sm:text-5xl hover:text-yellow-500 hover:scale-110 dark:text-white
                dark:hover:text-yellow-500 " 
                />
              <span className="font-medium hover:text-yellow-400 text-center">JavaScript</span>  
              </div>

              <div className="text-gray-600 dark:text-white flex flex-col justify-center items-center">
              <DiReact 
              className="text-gray-600 text-4xl sm:text-5xl hover:text-blue-300 hover:scale-110 dark:text-white
                dark:hover:text-blue-300" 
                />
              <span className="font-medium hover:text-blue-400">React</span>  
              </div>

              <div className="text-gray-600 dark:text-white flex flex-col justify-center items-center mt-8">
              <DiJava 
              className="text-gray-600 text-4xl sm:text-5xl hover:text-red-500 hover:scale-110 dark:text-white
                dark:hover:text-red-500" 
                />
              <span className="font-medium hover:text-red-400">Java</span>  
              </div>

              <div className="text-gray-600 dark:text-white flex flex-col justify-center items-center mt-8">
              <DiPython 
              className="text-gray-600 text-4xl sm:text-5xl hover:text-blue-500 hover:scale-110 dark:text-white
                dark:hover:text-blue-500" 
                />
              <span className="font-medium hover:text-blue-500">Python</span>  
              </div>

              <div className="text-gray-600 dark:text-white flex flex-col justify-center items-center mt-8">
              <DiPostgresql 
              className="text-gray-600 text-4xl sm:text-5xl hover:text-sky-700 hover:scale-110 dark:text-white
                dark:hover:text-sky-700" 
                />
              <span className="font-medium hover:text-sky-700">PostgreSQL</span>  
              </div>
              
              <div className="text-gray-600 dark:text-white flex flex-col justify-center items-center mt-8">
              <DiGit 
              className="text-gray-600 text-4xl sm:text-5xl hover:text-red-400 hover:scale-110 dark:text-white
                dark:hover:text-red-400" 
                />
              <span className="font-medium hover:text-blue-400">Git</span>  
              </div>
              
              <div className="text-gray-600 dark:text-white flex flex-col justify-center items-center mt-10">
              <SiSpringboot 
              className="text-gray-600 text-3xl sm:text-4xl hover:text-lime-500 hover:scale-110 dark:text-white
              dark:hover:text-lime-500" 
              />
              <span className="font-medium hover:text-lime-500">Spring Boot</span>  
              </div>

              <div className="text-gray-600 dark:text-white flex flex-col justify-center items-center mt-10">
              <IoLogoFirebase 
              className="text-gray-600 text-3xl sm:text-4xl hover:text-yellow-400 hover:scale-110 dark:text-white
                dark:hover:text-yellow-500" 
                />
              <span className="font-medium hover:text-yellow-400">Firebase</span>  
              </div>

              <div className="text-gray-600 dark:text-white flex flex-col justify-center items-center mt-10">
              <SiPostman 
              className="text-gray-600 text-3xl sm:text-4xl hover:text-orange-500 hover:scale-110 dark:text-white
                dark:hover:text-orange-500" 
                />
              <span className="font-medium hover:text-orange-400">Postman</span>  
              </div>

              <div className="text-gray-600 dark:text-white flex flex-col justify-center items-center mt-10">
              <SiTailwindcss 
              className="text-gray-600 text-3xl sm:text-4xl hover:text-cyan-500 hover:scale-110 dark:text-white
                dark:hover:text-cyan-500" 
                />
              <span className="font-medium hover:text-cyan-400">Tailwind</span>  
              </div>
              
            </div>

          </div>

        </section>

        <section className="pt-10">
          <div className="m-10">
            <h3 id="projects"
            className="text-center text-4xl md:text-5xl font-medium  text-black dark:text-white">
              Projects
            </h3>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 2xl:grid-cols-4 gap-12">



            <div className="text-center shadow-xl hover:shadow-inner p-10  rounded-xl my-10 
              dark:shadow-gray-800">
                
              <Image className="lg:hover:scale-150 rounded-lg lg:hover:-translate-y-10 transition-all duration-700 ease-in-out
              touch-pinch-zoom md:touch-none" 
              src={worldpinimage} layout='responsive' />
              
              <h3 className="text-xl font-bold pt-4 pb-4 text-black dark:text-white">
                WorldPin
              </h3>
              <div>
                <ul className="grid grid-cols-2 content-center gap-2 px-1 py-1 ">
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base 
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white
                    ">
                    React
                  </li>
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white">
                    Java
                  </li>
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white">
                    PostgreSQL
                  </li>
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white">
                    Firebase
                  </li>
                </ul>
              </div>
              <p className="py-5 text-black dark:text-gray-300">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae
                fugiat corrupti dignissimos numquam. Totam, voluptate! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Similique commodi libero maxime quis necessitatibus, sint ab quos dolore illum eveniet.
              </p>
              <div>
                <ul className="grid grid-cols-2 align-center gap-1 sm:gap-4 sm:px-1 py-1 
                  2xl:max-3xl:grid-rows-2 2xl:max-3xl:grid-cols-1">
                  <li className="xl:text-lg text-white font-semibold bg-gray-800 hover:bg-gray-900  
                    outline outline-2 hover:outline-0 rounded-full transition-all duration-300
                    dark:hover:bg-gray-700 dark:hover:outline-gray-800 hover:scale-95 dark:outline-gray-800">
                    &nbsp;&nbsp;Live Demo {'>'}&nbsp;&nbsp;
                  </li>
                  <li className="xl:text-lg text-white font-semibold bg-gray-800 hover:bg-gray-900  
                    outline outline-2  hover:outline-0 rounded-full transition-all duration-300
                    dark:hover:bg-gray-700 dark:hover:outline-gray-800 hover:scale-95 dark:outline-gray-800">

                    <a href='https://github.com/faizanahmkhan/worldpin_app' target='_blank'  > 
                    &nbsp;&nbsp;GitHub {'>'}&nbsp;&nbsp;
                    </a> 

                  </li>
                </ul>
                </div>
            </div>


            <div className="text-center shadow-xl hover:shadow-inner p-10 rounded-xl my-10 
              dark:shadow-gray-800
              ">
                
              <Image className="lg:hover:scale-150 rounded-lg lg:hover:-translate-y-10 transition-all duration-700 ease-in-out
              touch-pinch-zoom md:touch-none" 
              src={worldpinimage} layout='responsive' />
              
              <h3 className="text-xl font-bold pt-4 pb-4 text-black dark:text-white">
                WorldPin
              </h3>
              <div>
                <ul className="grid grid-cols-2 content-center gap-2 px-1 py-1 ">
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base 
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white
                    ">
                    React
                  </li>
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white">
                    Java
                  </li>
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white">
                    PostgreSQL
                  </li>
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white">
                    Firebase
                  </li>
                </ul>
              </div>
              <p className="py-5 text-black dark:text-gray-300">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae
                fugiat corrupti dignissimos numquam. Totam, voluptate! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Similique commodi libero maxime quis necessitatibus, sint ab quos dolore illum eveniet.
              </p>
              <div>
                <ul className="grid grid-cols-2 align-center gap-1 sm:gap-4 sm:px-1 py-1 
                2xl:max-3xl:grid-rows-2 2xl:max-3xl:grid-cols-1">
                  <li className="xl:text-lg text-white font-semibold bg-gray-800 hover:bg-gray-900  
                    outline outline-2 hover:outline-0 rounded-full transition-all duration-300
                    dark:hover:bg-gray-700 dark:hover:outline-gray-800 hover:scale-95 dark:outline-gray-800">
                    &nbsp;&nbsp;Live Demo {'>'}&nbsp;&nbsp;
                  </li>
                  <li className="xl:text-lg text-white font-semibold bg-gray-800 hover:bg-gray-900  
                    outline outline-2  hover:outline-0 rounded-full transition-all duration-300
                    dark:hover:bg-gray-700 dark:hover:outline-gray-800 hover:scale-95 dark:outline-gray-800">

                    <a href='https://github.com/faizanahmkhan/worldpin_app' target='_blank'  > 
                    &nbsp;&nbsp;GitHub {'>'}&nbsp;&nbsp;
                    </a> 

                  </li>
                </ul>
                </div>
            </div>


            <div className="text-center shadow-xl hover:shadow-inner p-10 rounded-xl my-10 
              dark:shadow-gray-800
              ">
                
              <Image className="lg:hover:scale-150 rounded-lg lg:hover:-translate-y-10 transition-all duration-700 ease-in-out
              touch-pinch-zoom md:touch-none" 
              src={worldpinimage} layout='responsive' />
              
              <h3 className="text-xl font-bold pt-4 pb-4 text-black dark:text-white">
                WorldPin
              </h3>
              <div>
                <ul className="grid grid-cols-2 content-center gap-2 px-1 py-1 ">
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base 
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white
                    ">
                    React
                  </li>
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white">
                    Java
                  </li>
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white">
                    PostgreSQL
                  </li>
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white">
                    Firebase
                  </li>
                </ul>
              </div>
              <p className="py-5 text-black dark:text-gray-300">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae
                fugiat corrupti dignissimos numquam. Totam, voluptate! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Similique commodi libero maxime quis necessitatibus, sint ab quos dolore illum eveniet.
              </p>
              <div>
                <ul className="grid grid-cols-2 align-center gap-1 sm:gap-4 sm:px-1 py-1 
                2xl:max-3xl:grid-rows-2 2xl:max-3xl:grid-cols-1">
                  <li className="xl:text-lg text-white font-semibold bg-gray-800 hover:bg-gray-900  
                    outline outline-2 hover:outline-0 rounded-full transition-all duration-300
                    dark:hover:bg-gray-700 dark:hover:outline-gray-800 hover:scale-95 dark:outline-gray-800">
                    &nbsp;&nbsp;Live Demo {'>'}&nbsp;&nbsp;
                  </li>
                  <li className="xl:text-lg text-white font-semibold bg-gray-800 hover:bg-gray-900  
                    outline outline-2  hover:outline-0 rounded-full transition-all duration-300
                    dark:hover:bg-gray-700 dark:hover:outline-gray-800 hover:scale-95 dark:outline-gray-800">

                    <a href='https://github.com/faizanahmkhan/worldpin_app' target='_blank'  > 
                    &nbsp;&nbsp;GitHub {'>'}&nbsp;&nbsp;
                    </a> 

                  </li>
                </ul>
                </div>
            </div>


            <div className="text-center shadow-xl hover:shadow-inner p-10 rounded-xl my-10 
              dark:shadow-gray-800
              ">
                
              <Image className="lg:hover:scale-150 rounded-lg lg:hover:-translate-y-10 transition-all duration-700 ease-in-out
              touch-pinch-zoom md:touch-none" 
              src={worldpinimage} layout='responsive' />
              
              <h3 className="text-xl font-bold pt-4 pb-4 text-black dark:text-white">
                WorldPin
              </h3>
              <div>
                <ul className="grid grid-cols-2 content-center gap-2 px-1 py-1 ">
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base 
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white
                    ">
                    React
                  </li>
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white">
                    Java
                  </li>
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white">
                    PostgreSQL
                  </li>
                  <li className="text-teal-600 font-semibold hover:bg-teal-600 hover:text-white  
                    outline outline-2 outline-teal-600 rounded-lg text-base
                    dark:text-pink-400 dark:outline-pink-400 dark:hover:bg-pink-400 dark:hover:text-white">
                    Firebase
                  </li>
                </ul>
              </div>
              <p className="py-5 text-black dark:text-gray-300">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae
                fugiat corrupti dignissimos numquam. Totam, voluptate! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Similique commodi libero maxime quis necessitatibus, sint ab quos dolore illum eveniet.
              </p>
              <div>
                <ul className="grid grid-cols-2 align-center gap-1 sm:gap-4 sm:px-1 py-1 
                2xl:max-3xl:grid-rows-2 2xl:max-3xl:grid-cols-1">
                  <li className=" xl:text-lg text-white font-semibold bg-gray-800 hover:bg-gray-900  
                    outline outline-2 hover:outline-0 rounded-full transition-all duration-300
                    dark:hover:bg-gray-700 dark:hover:outline-gray-800 hover:scale-95 dark:outline-gray-800">
                    Live Demo {'>'}
                  </li>
                  <li className=" xl:text-lg  text-white font-semibold bg-gray-800 hover:bg-gray-900  
                    outline outline-2  hover:outline-0 rounded-full transition-all duration-300
                    dark:hover:bg-gray-700 dark:hover:outline-gray-800 hover:scale-95 dark:outline-gray-800">

                    <a href='https://github.com/faizanahmkhan/worldpin_app' target='_blank'  > 
                    GitHub {'>'}
                    </a> 

                  </li>
                </ul>
                </div>
            </div>

            
          </div>
        </section>

        <section className="pt-10">
          <div className="m-10">
            <h3 id="projects"
            className="text-center text-4xl md:text-5xl font-medium  text-black dark:text-white">
              Contact Me
            </h3>
          </div>
              

        </section>

      </main>
    </div>
  );
}
