import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Faizan Khan Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800">
        <div >
          <section className="min-h-screen">
            <nav className="py-10 mb-12 flex justify-between">
              <h1 className="text-xl text-black">Created with React</h1>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl text-black" />
                </li>
                <li>
                  <a
                    className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                    href="#"
                  >
                    Resume
                  </a>
                </li>
              </ul>
            </nav>
            <div className="text-center p-10 py-10">
              <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
                Faizan Khan
              </h2>
              <h3 className="text-2xl py-2 text-black md:text-3xl">Developer and designer</h3>
              <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis
                natus suscipit vel ipsam rerum dolorem harum. Voluptates ab
                nulla consectetur!
              </p>
            </div>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
            <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
              <Image src={deved} layout='fill' objectFit="cover" />
            </div>
          </section>
          
          <section>
            <div>
            <h3 className="text-3xl py-1 text-black">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi cum ea temporibus, <span className='text-teal-400'> facilis voluptates sint</span> eum voluptatibus dolorum, doloremque iure maxime quia obcaecati dolorem eius modi. Laborum corporis molestias laboriosam reprehenderit? Voluptate nobis, minima inventore repellendus deserunt cupiditate obcaecati repellat.
            </p>
            </div>
            <div className="lg:flex gap-10">
              <div className="text-center shadow-lg p-10 rounded-xl my-10">
                <Image src={design} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2 text-black">Beautiful Designs</h3>
                <p className="py-2 text-black">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae fugiat corrupti dignissimos numquam. Totam, voluptate!
                </p>
                <h4 className="py-4 text-teal-400">Design Tools I used</h4>
                <p className="text-gray-800 py-1">React</p>
                <p className="text-gray-800 py-1">React</p>
                <p className="text-gray-800 py-1">React</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10">
                <Image src={code} width={100} height={100}/>
                <h3 className="text-lg font-medium pt-8 pb-2 text-black">Beautiful Designs</h3>
                <p className="py-2 text-black">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae fugiat corrupti dignissimos numquam. Totam, voluptate!
                </p>
                <h4 className="py-4 text-teal-400">Design Tools I used</h4>
                <p className="text-gray-800 py-1">React</p>
                <p className="text-gray-800 py-1">React</p>
                <p className="text-gray-800 py-1">React</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10">
                <Image src={consulting} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2 text-black">Beautiful Designs</h3>
                <p className="py-2 text-black">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae fugiat corrupti dignissimos numquam. Totam, voluptate!
                </p>
                <h4 className="py-4 text-teal-400">Design Tools I used</h4>
                <p className="text-gray-800 py-1">React</p>
                <p className="text-gray-800 py-1">React</p>
                <p className="text-gray-800 py-1">React</p>
              </div>
            </div>
          </section>
          <section>
            <div>
              <h3 className="text-3xl py-1 text-black">Portfolio</h3>
              <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi cum ea temporibus, <span className='text-teal-400'> facilis voluptates sint</span> eum voluptatibus dolorum, doloremque iure maxime quia obcaecati dolorem eius modi. Laborum corporis molestias laboriosam reprehenderit? Voluptate nobis, minima inventore repellendus deserunt cupiditate obcaecati repellat.
            </p>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1"><Image src={web1} className='rounded-lg object-cover' width={'100%'} height='{100%}'/></div>
              <div className="basis-1/3 flex-1"><Image src={web2} className='rounded-lg object-cover' width={'100%'} height='{100%}'/></div>
              <div className="basis-1/3 flex-1"><Image src={web3} className='rounded-lg object-cover' width={'100%'} height='{100%}'/></div>
              <div className="basis-1/3 flex-1"><Image src={web4} className='rounded-lg object-cover' width={'100%'} height='{100%}'/></div>
              <div className="basis-1/3 flex-1"><Image src={web5} className='rounded-lg object-cover' width={'100%'} height='{100%}'/></div>
              <div className="basis-1/3 flex-1"><Image src={web6} className='rounded-lg object-cover' width={'100%'} height='{100%}'/></div>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
