import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import deved from '../public/dev-ed-wave.png';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Faizan Khan Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
      <main className="bg-white px-10">
        <div >
          <section className="min-h-screen">
            <nav className="py-10 mb-12 flex justify-between">
              <h1 className="text-xl text-black">Created with React</h1>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill className="cursor-pointer text-2xl text-black" />
                </li>
                <li>
                  <a
                    className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                    href="#"
                  >
                    Resume
                  </a>
                </li>
              </ul>
            </nav>
            <div className="text-center p-10 py-10">
              <h2 className="text-5xl py-2 text-teal-600 font-medium">
                Faizan Khan
              </h2>
              <h3 className="text-2xl py-2">Developer and designer</h3>
              <p className="text-md py-5 leading-8 text-gray-800">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis
                natus suscipit vel ipsam rerum dolorem harum. Voluptates ab
                nulla consectetur!
              </p>
            </div>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
            <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
              <Image src={deved} layout='fill' objectFit="cover" />
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
